# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SDWebImage', '~>3.7'
pod 'Alamofire', '~> 1.3'
